### ISSUE TITLE
Missing fields in .txconfig file. Version is required. Publisher is required.

### ISSUE THREAD

**Issue by Erlix322** [textX/textX-LS#17]
I have the following .txconfig in my project folder, but the Command to run the extension generation throws the following error:Missing fields in .txconfig file. Version is required. Publisher is required.

dsl hello [hello] {
    general {
        author: "Eric"        
        version: "0.0.1"
    }
    
    paths {
        grammar:"./hello.tx"
    }
}

**Comment by danixeee** [comment]
@Erlix322 I didn't see this issue, sorry. This is the new extension that is still under development and is not published yet. It won't need any configuration files.

When generating extension, you need to supply _version_ and _publisher_ fields, because those are required by VSCode manifest file, if I remember correctly.
